src/lib.rs
Fixes missing [code syntax highlighting](https://unicode-rs.github.io/unicode-segmentation/unicode_segmentation/trait.UnicodeSegmentation.html#tymethod.unicode_words)
=> Add missing code fencing

.travis.yml, Cargo.toml, README.md, scripts/unicode.py, src/grapheme.rs, src/lib.rs, src/tables.rs, src/test.rs, src/word.rs
All of the libcore functionality used in this crate is now stable, so it is no longer necessary to disable it for compatibility with the Rust stable channel.
=> Make no_std the default; remove optional Cargo feature

Cargo.toml, README.md, src/grapheme.rs, src/lib.rs, src/word.rs
This is based on standard library methods like [Chars::as_str][1].
[1]: https://doc.rust-lang.org/std/str/struct.Chars.html#method.as_str
=> Add as_str methods to iterator types

Cargo.toml
Semimajor bump because of the extra rope API. No breaking changes, but it deserves a fresh version. Will make it 1.1.1 instead if y'all think that should be the case.
r? @SimonSapin @kwantam
=> Bump to 1.2.0

src/grapheme.rs
This PR fixes two cases where provide_context panics even though the previous call of `is_boundary` returns a PreContext error.
The primary cause is `provide_context` assumes its state as Regional or Emoji; otherwise it gets panicked with 'invalid state!'
However:
- if the chunk starts with the cursor position, it requires pre-context for `cat_before` regardless of its state (and that's necessary for some cases indeed). so provide_context should fill `cat_before` in such case.
- if both `cat_before` and `cat_after` are RIS and the boundary is undecided by the chunk, it requires pre-context but it does not set its state to Regional. This is done by setting state within `handle_regional`.
=> Fix patterns of provide_context gets panicked

src/grapheme.rs
=> fix crashes on prev_boundary

.travis.yml
The 1.2.0 release increased the minimum supported version of Rust from
below 1.11.0 to 1.13.0 due to the introduction of code that use the
"?" operator. This caused unexpected build failures in dependent
crates, such as clap.
This PR updates Travis to also test against the current minimum
version. Changes to this version will thus fail PRs and it will become
an active decision to bump the minimum supported Rust version.
Between this PR was originally made and today, the minimum version
increased further and the earliest version where I can get the crate
to compile is now Rust 1.24.0.
Fixes #26.
=> travis: also test with minimum supported Rust version

Cargo.toml, README.md, tests/version-numbers.rs
This adds a test that will check the examples in README.md for the
current package version.
It also checks that there is a Markdown heading mentioning (at least)
the current version. This serves as a simple check that the change log
section is updated when the version number is bumped.
Related to #30, #41, #47, and #48.
=> Ensure version number consistency

README.md
This seems to have been forgotten in 703e9c25.
This was originally proposed in #27, but got reverted in a91ee39 along with other changes.
=> readme: add changelog for 1.2.1

src/lib.rs
Update doc version to match current version. 
I noticed this was out of date on the doc page: https://unicode-rs.github.io/unicode-segmentation/unicode_segmentation/index.html
I think the generated source the the website will need to get updated after this: https://github.com/unicode-rs/unicode-rs.github.io
=> Update version in docs to 1.2.1

README.md, src/lib.rs
This PR just updates the docs from specifying `1.3.0` to `1.6.0`, so if folks are copy/pasting (like me), there's less surprises.
=> Update docs to point to current version

scripts/unicode.py, src/grapheme.rs, src/sentence.rs, src/tables.rs, src/word.rs
Typical text involves a lot of chars one-after-another that
are in a similar scalar value range and in the same category.  This
commit takes advantage of that to speed up grapheme iteration by
caching the range and category of the last char, and always checking
against that cache first before doing a binary search on the whole
grapheme category table.
This results in significant speed ups on many texts, in some cases
up to 2x faster.
=> Optimization for grapheme iteration.

src/grapheme.rs
This speeds up processing even for many non-ascii texts, since
they often still use ascii-range punctuation and whitespace.
=> Implement a special-case lookup for ascii grapheme categories.

src/grapheme.rs, src/sentence.rs, src/word.rs
The Rust standard library has a nice practice for documentation for public structs. Documentation for these structs include links to the method that creates them. This is very useful for beginners who may stumble upon the documentation for the struct when they would really like documentation for the method.
Add documentation for all of the structs that are created by methods on the `UnicodeSegmentation` trait with links back to the creating methods.
=> Link to creating methods in struct documentation

src/lib.rs
It looks like the doc comments for `unicode_sentences` and `split_sentence_bounds` got mixed up. I swapped them so that each function is described correctly.
I also added examples illustrating the difference between the three functions for segmenting sentences.
=> Improve docs for sentence segmentation

src/lib.rs, src/word.rs
The PR adds a new iterator: `UnicodeWordIndices` (and the function `unicode_word_indices`). It is similar to `UnicodeWords` but also provides byte offsets for each word.
The motivation for this PR was making https://github.com/jonathandturner/reedline/pull/5 in which I used `split_word_bound_indices` and then filtered the result using logic that is internal to `unicode_words`. I believe that PR would have been trivial using `unicode_word_indices`. Hopefully it can also be useful to others.
Should I add more tests for `unicode_word_indices`? Or are the existing tests for `unicode_words` and the doc test for `unicode_word_indices` sufficient?
=> Add unicode_word_indices

src/word.rs
While it's a cosmetic change by making the variable immutable, it might improve codegen by more correct lifetime tracking and makes code less error prone.
=> Made local variable immutable by moving it into loop

Cargo.toml, scripts/unicode.py, src/grapheme.rs, src/sentence.rs, src/tables.rs, src/test.rs, src/word.rs
I also updated the edition to 2018 since this PR does the same changes as #59 and, therefore, this PR supersedes the staled one.
=> Fixed unused imports and deprecated pattern warnings

src/grapheme.rs
Uses `#[derive(Debug)]`. Another option would be to make use of `to_str()`.
=> Implement Debug for Graphemes (#95)

Cargo.toml, benches/graphemes.rs, src/grapheme.rs
This PR increases the number of (internal) functions that are given an opportunity to be inlined during grapheme detection.
Benchmarking indicates that this change results in a significant performance improvement (see below).
This PR also replaces bencher with criterion to enable continued performance monitoring.
```
$ cargo criterion
Compiling unicode-segmentation v1.7.1 (/home/tim/Open/unicode-segmentation)
Finished bench [optimized] target(s) in 2.96s
Gnuplot not found, using plotters backend
Benchmarking graphemes_arabic: Collecting 100 samples in estimated 6.2276 s                                                                            graphemes_arabic         time:   [300.59 us 303.65 us 306.84 us]
change: [-28.120% -27.089% -26.073%] (p = 0.00 < 0.05)
Performance has improved. …
```
=> Increase the #[inline] opportunities - 15-40% performance improvements

Cargo.toml, benches/unicode_words.rs, benches/word_bounds.rs
The word boundary extensions to &str/String behave in a very similar, but not identical manner to `.graphemes()`. For example, Mandarin to slow(ish) on `.graphemes()` but
fast(ish) on .word_boundaries() whereas languages with whitespace-delimited words tend to have the same performance characteristics with the latter methods.
As the library develops, it would be worthwhile to monitor the speed of the rest of the documented API.
Out of interest, here are the results of local benchmarking:
```
Running unittests (target/release/deps/graphemes-564b84453b2889b6)
running 8 tests
test graphemes_arabic      ... bench:     569,134 ns/iter (+/- 67,321) = 88 MB/s
test graphemes_english     ... bench:     772,797 ns/iter (+/- 72,533) = 64 MB/s
test graphemes_hindi       ... bench:     557,920 ns/iter …
```
=> Benchmark other methods mentioned in README

src/sentence.rs, src/word.rs
I don't expect this to noticeably impact performance either positively or negatively for most use-cases, especially because `Iterator::collect` relies on the lower bound of `size_hint` which will remain unchanged after this PR.
However the upper bound will go from `None` to `Some(upper)`, which may benefit downstream crates that use it as a heuristic for pre-allocation size.
Note also that I forwarded the implementation of `size_hint` to the inner iterator, which means it is UAX#29 agnostic. I'm not enough of a Unicode expert to know if e.g. word boundaries can be empty, so it may not be the tightest possible upper bound for longer strings.
=> Adding missing size_hint for UnicodeSentences, UnicodeWords, and UnicodeWordIndices

Cargo.toml
The documentation on `unicode-rs.github.io` hasn't been updated in three
years (since Travis CI stopped working), and docs.rs works fine for this
crate.
=> Remove outdated documentation link in Cargo.toml

src/grapheme.rs, src/sentence.rs, src/word.rs
Some types in this crate don't have Debug implemented, but it's annoying
to use a non-Debug type in a struct with Debug derived. I just used the
automatic impl from `#[derive(Debug)]` for all of these (although in the
future it might be good to have custom implementations for types with
complex internals).
Closes #95.
=> Implement Debug on all public structs

scripts/unicode.py, src/tables.rs
…as long as the Unicode versions match
=> Use stdlib alphabetic and numeric character tables

src/grapheme.rs
Fix 6 arithmetic overflow panics in #119 
Wrap operations with safer functions to deal with edge cases.
=> Fix arithmetic overflow panics

src/grapheme.rs
Fix unwrap panic in #119 
Add check for iter.next() to avoid panic in unwrap.
=> Fix unwrap panic in next_boundary()

Cargo.toml, benches/chars.rs, benches/texts/log.txt, benches/unicode_word_indices.rs, benches/word_bounds.rs, benches/words.rs, src/lib.rs, src/word.rs
This PR adds a fast path for `unicode_word_indices` and `unicode_words`. 
* Add ascii version behind ascii check
* Add benchmark
* Add enum Iterator to wrap ascii and non-ascii into a single iterator
* Add proptest to make sure ascii and non-ascii methods behave exactly the same.
Performance for ASCII text is greatly improved, while everything else gets a slight performance hit.
```
unicode_word_indices/log
time:   [209.68 ns 212.35 ns 215.32 ns]
thrpt:  [761.82 MiB/s 772.45 MiB/s 782.29 MiB/s]
change:
time:   [-82.313% -82.117% -81.888%] (p = 0.00 < 0.05)
thrpt:  [+452.12% +459.18% +465.38%]
Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
3 (3.00%) high mild
unicode_word_indices/english
time:   [426.95 µs 428.03 µs 429.18 µs]
thrpt:  [110.42 MiB/s 110.72 MiB/s …
```
=> Add ascii fast path for unicode_word_indices and unicode_words
